#ifndef LIBRIBBONUI_GLOBAL_H
#define LIBRIBBONUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBRIBBONUI_LIBRARY)
#  define LIBRIBBONUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBRIBBONUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBRIBBONUI_GLOBAL_H
